### ISSUE TITLE
Choosing the right tools to front-end development.

### ISSUE THREAD

**Issue by jdinartejesus** [open-source-society/ossu-ui#1]
Hey guys,  about front-end I would recommend this tools:

Framework: Reactjs
Bundler: Webpack
App-architecture: Flux, redux or Baconjs
Testing: Maybe Jest
HTML: Jade, or Html?
CSS: Stylus or Sass?

Note: I'm also starting was a front-end developer, maybe, someone with experience have a better idea. 

Greetings!

**Comment by SoullessWaffle** [comment]
I vote we use Semantic UI as CSS framework, that way we can just define the design structure once and theme it afterwards

**Comment by jdinartejesus** [comment]
What about using http://material-ui.com/#/, if we use Reactjs of course.
For HTML we could also use Jade, I really liked the simplicity. http://jade-lang.com/

**Comment by jdinartejesus** [comment]
I never used, but is if possible to create our own or use other themes. Sounds good to me.
I'll take a look how it works! 

Thanks @SoullessWaffle

**Comment by SoullessWaffle** [comment]
@jdinartejesus I do like Jade and I have experience using it, but I'm not sure the rest of the front-end team does. I'll ask in the main issue thread since that's what most people are subscribed to.

**Comment by ericdouglas** [comment]
Another important topic is about ES2015 or ES5.

I'd suggest go with **ES2015**!

**Comment by SoullessWaffle** [comment]
@ericdouglas Yes, definitely. ES2015 is the way to go.

**Comment by jdinartejesus** [comment]
@SoullessWaffle  Do you wanna create a table with the stuff we already decide? :joy:

**Comment by jdinartejesus** [comment]
Ok I created some basic files and general for start working. I'm going to use Git workflow. Also recommend for PR to be merge to develop at least TWO :+1:  and for master THREE :+1: ? 

Tell me what do you think guys!

@SoullessWaffle @ericdouglas

**Comment by ericdouglas** [comment]
@jdinartejesus this is necessary, indeed.

Maybe ONE or TWO :+1: for develop and TRHEE :+1: for master.

**Comment by SoullessWaffle** [comment]
@ericdouglas Assuming a :+1: is an approval by another contributor, then yes, that sounds about right.

@jdinartejesus [your wish is my command](https://github.com/open-source-society/computer-science/issues/81#issuecomment-147093520) ;)

**Comment by jdinartejesus** [comment]
:+1:

**Comment by jbhum** [comment]
I think that redux is awesome. I haven't had the chance to do much with it yet, but I have seen some really cool developer experience stuff with it. My vote is definitely for using redux!

**Comment by jbhum** [comment]
I would also probably go with just plain html. I like the jade syntax, but I traditionally just prefer to see my code in html, also it makes it easier if we are using jsx not to have to use jade sometimes and "jsx html" other times. To me it just makes more sense that way, but if you disagree let me know for sure.

**Comment by jdinartejesus** [comment]
@jbhum I also would like to use something like Reflux or Redux. 

@SoullessWaffle do you wanna create one of those fancy tables with all the confirmed technologies for front-end?

**Comment by jbhum** [comment]
So, What we have right now is.
- React for rendering the view
- Redux for data flow and control
- Webpack and Babel for compiling and packaging
- Redux-Router or React-Router for in app route handling
- ES2015 FTW!!!!
- For now, we are not really using a html templating language because it all happens in the react magic. If we need it in the future we will look into it.
- Sematic-ui for the css libraries

This is what we have so far. and gives us pretty good coverage. I don't have any testing tools listed, because I don't really know what is good in that area and I will let someone else worry about that.
