### ISSUE TITLE
React-tools dependency unnecessary?

### ISSUE THREAD

**Issue by detrohutt** [open-source-society/ossu-ui#14]
When following the directions to clone the project, I got stuck at the "npm install" part with a peer dependency error.

I couldn't find anywhere in the code directly referencing react-tools.. upon removing its dependency from package.json I was able to get the project up and running.

Maybe @jbhum could verify the need for this as he appears to be the one who added it.

**Comment by jbhum** [comment]
I added it by accident and it should be taken out. react-tools has been deprecated in favor of babel transpiler. I think there will still be warnings when you take it out because some of the packages think they need it, but it works fine with out it to my knowledge. Thanks for catching that.

**Comment by detrohutt** [comment]
No problem, I made a pull request :)
