### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by SoullessWaffle** [open-source-society/ossu-ui#4]
What code style are we using for the project?
I vote we use the [JavaScript Standard][jss] style for the JS. It even comes with a nice badge :)

[jss]: https://github.com/feross/standard

**Comment by ericdouglas** [comment]
:+1:

**Comment by evanplaice** [comment]
I second that.

Looks like enforcing it using editorconfig alone is going to be an issue.
https://github.com/feross/standard/issues/153

If we decide to go this route, can we get the ossu-ui editorconfig updated to reflect? That'll make it easier to copy over to ossu-api

**Comment by SoullessWaffle** [comment]
We can also add `standard` to the `npm test` command so it yells at you if you break convention.

**Comment by evanplaice** [comment]
:+1:

**Comment by 007lva** [comment]
+1 for [Standard](https://github.com/feross/standard) but we also need to fit this with the [codeclimate](https://codeclimate.com/) or [codacy](https://www.codacy.com/) linter config

**Comment by SoullessWaffle** [comment]
We're considering [SemiStandard](https://github.com/Flet/semistandard) right now because of the semicolons. Personally, I'm fine with either.

**Comment by jdinartejesus** [comment]
:+1: I agree having Standard

**Comment by ericdouglas** [comment]
:+1: semicolons

**Comment by jbhum** [comment]
It looks most people over in the slack are in agreement on using SemiStandard https://github.com/Flet/semistandard

**Comment by evanplaice** [comment]
:+1: 

I'm working on updating CONTRIBUTING.md on ossu-api. Stay tuned to replicate the changes in ossu-ui.

**Comment by evanplaice** [comment]
OK, Done...

https://github.com/open-source-society/ossu-ui/pull/5

Can I get somebody from the ossu-ui team to approve this? I'd merge it myself but I want to verify that it's in line with the goals of ossu-ui.
