### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by waterlooSunset** [open-source-society/ossu-ui#6]
Anyone want to chit-chat, yik yak, or squabble about color schemes?

Right now the OSS University logo has:

hex# 3498db (background)
hex# fff (OSS)
hex# 20124d (university)

A strong start, but we'll need more than 3 colors at some point. So... where are going? Let us discuss!

**Comment by waterlooSunset** [comment]
@trevor on the slack channel has added #ADD8E6 to the list. A nice light blue for a background color to use within the app.

**Comment by trevor** [comment]
:heart_eyes:
